export enum SerialMessageTypeInterface {
  DEVICE_CHECK = 'DEVICE_CHECK',
  START_PAIR = 'START_PAIR',
  END_PAIR = 'END_PAIR',
  PAIR_CLICKER = 'PAIR_CLICKER',
  START_POLL = 'START_POLL',
  ENABLE_MULTI_MODE = 'ENABLE_MULTI_MODE',
  DISABLE_MULTI_MODE = 'DISABLE_MULTI_MODE',

  // MyNote: Firmware Updating Commands
  // Common
  READY_FOR_TRANSMISSION = 'READY_FOR_TRANSMISSION',

  // Update Receiver
  UPDATE_RECEIVER = 'UPDATE_RECEIVER',
  RECEIVER_OTA_CHUNK = 'RECEIVER_OTA_CHUNK',
  RECEIVER_OTA_ACK = 'RECEIVER_OTA_ACK',
  RECEIVER_OTA_TRANSMISSION_COMPLETE = 'RECEIVER_OTA_TRANSMISSION_COMPLETE',

  // Update Clicker
  UPDATE_CLICKER = 'UPDATE_CLICKER',
  CLICKER_OTA_CHUNK = 'CLICKER_OTA_CHUNK',
  CLICKER_OTA_ACK = 'CLICKER_OTA_ACK',
  CLICKER_OTA_TRANSMISSION_COMPLETE = 'CLICKER_OTA_TRANSMISSION_COMPLETE',
  STOP_UPDATE_CLICKER = 'STOP_UPDATE_CLICKER',
}
