import '../Dependencies/ipc/ipc.main'
import '../Dependencies/ElectronStore/ElectronStore.main'
import '../Dependencies/env/env.main'
import '../Dependencies/OTA/OTA.main'
import '../Dependencies/AppInfo/AppInfo.main'
import '../Dependencies/SecondaryWindow/SecondaryWindow.main'